### ISSUE TITLE
流量识别论文

### ISSUE THREAD

**Issue by wongsyrone** [shadowsocks/shadowsocks-org#81] opened 2017-09-11 10:31 UTC
https://arxiv.org/pdf/1709.02656.pdf

https://arxiv.org/abs/1709.02656

**Comment by Mygod** [comment] 2017-09-11 15:36
https://arxiv.org/pdf/1312.6199v1.pdf

**Comment by madeye** [comment] 2017-09-12 01:19
If we consider encryption as a function `f(x)` (linear or non-linear doesn't matter), it's not surprising that DNN also works here to detect the underlying characters in the cipher text.

**Comment by Mygod** [comment] 2017-09-12 01:26
@madeye Incorrect. Since neural network evaluation is a polynomial time algorithm (assuming all assumptions in modern cryptography holds), it can only classify packet content as random noise. Look at section 5 where they said they failed to classify Tor traffic.

**Comment by wongsyrone** [comment] 2017-09-12 01:57
I'm not expert on this. Just cite a paragraph I think matters.

> Ideal encryption technique

AEAD and other schemes developed by crypto experts

> causes the data to bear most possible entropy [47]. In other
words, it produces pattern-less data that theoretically can
not be discernible form on another. 

Tools like sssniff

> However due to the
fact that all encryption schemes use pseudo-random generators, this hypothesis is not always true in practice. Each
application employs its own ciphering scheme for packets
encryption. These schemes utilize pseudo-random algorithms which bear distinct patterns. These patterns can
be used to distinguish applications from one another.

The initial intention of Shadowsocks: to be indistinguishable from random bytes
becomes the pattern being used to detect traffic.

-----

For Tor, if I understand it correctly, they know you are using Tor, but cannot determine the Tor payload, e.g., know if you are visiting Facebook, YouTube, etc. The payload doesn't matter at all; I can simply block connections.

**Comment by madeye** [comment] 2017-09-12 02:01
@Mygod Hmm, what I read is

> It is noticeable from Figs. 6a and 6b and Table 2 that Tor traffic was successfully classified.

**Comment by madeye** [comment] 2017-09-12 02:16
It's a little bit surprising that TOR can be detected with 100% recall and 100% precision.

![image](https://user-images.githubusercontent.com/627917/30305000-14c994f0-97a3-11e7-8a44-7d85f7792e32.png)

Two possible reasons:

1. TOR traffic is very different from other traffic, e.g. high entropy of the first packets like shadowsocks.
2. They are over-fitting. 😃

**Comment by Mygod** [comment] 2017-09-12 02:20
I'm just pointing out confidentiality makes classifying what's being transmitted via Tor hard. From 3.2, its input vector consists of:

* IP header;
* TCP/UDP header with zero paddings;
* First 1500 bytes of data with zero paddings.

Everything besides data which is random noise can be used to leak some information about what's being transmitted via Tor.

What @wongsyrone concerns is actually steganography. Yes confidentiality only makes distinguishing what's being transmitted hard.

**Comment by wongsyrone** [comment] 2017-09-12 02:20
Another thought on this.

The training requires data, which has to be pre-processed. Is there any way to make the data collection and processing difficult?

The packet length table shows there are many packets are zero-length. I'm not sure whether they are traffic control packet like ACK, SYN, etc or not.

**Comment by wongsyrone** [comment] 2017-09-12 02:40
From my observation, GFW prefers to cut off the root of a tree to make the censorship effectively.

DNS: send fake one just before the real response arrives.
HTTPS: reset connection after keywords being triggered.
Tor: block directory servers on the list, which can be collected via fake bridge or other kinds of abuse.

**Comment by Mygod** [comment] 2017-09-12 02:44
> However due to the
fact that all encryption schemes use pseudo-random generators, this hypothesis is not always true in practice. Each
application employs its own ciphering scheme for packets
encryption. These schemes utilize pseudo-random algorithms which bear distinct patterns. These patterns can
be used to distinguish applications from one another.

This author clearly does not know what's pseudorandomness. Whatever can be distinguished (within polynomial time of course) is not pseudorandomness. The real reason should be the fact that his input takes a lot of extra data from the packet, not just content.

@wongsyrone If GFW is actively interrupting connections, we can easily take countermeasures, even if they employ DNNs (see the paper I posted in the first comment).

**Comment by wongsyrone** [comment] 2017-09-12 02:50
> his input

The paper says the dataset is already labeled. Does it mean they already know something and just need to prove it instead distinguish one thing from others?

**Comment by Mygod** [comment] 2017-09-12 02:54
By the definition of classifying, no.

**Comment by Mygod** [comment] 2017-09-15 21:01
@wongsyrone This should be an interesting read for you: https://arxiv.org/pdf/cs/0702161.pdf

**Comment by zasdfgbnm** [comment] 2017-09-18 05:56
@Mygod Hmm... I don't think the computational indistinguishability of pseudorandom generators implies infeasibility to classify them in real world usage.

The definition of pseudorandom generator G is, for uniform distribution U, {G(U)} and {U} are computationally indistinguishable. Clearly, if you have two pseudorandom generator G and H, since both {G(U)} and {H(U)} are computationally indistinguishable with {U},  {G(U)} and {H(U)} are computationally indistinguishable with each other.

But in real world usage, the input of G and H are not uniform distribution U, but some something else instead, say the distribution of youtube videos. In this case, the output of G and H might be very different, making it possible to distinguish them from each other.

**Comment by Mygod** [comment] 2017-09-18 06:20
@zasdfgbnm I agree. But I didn't mention pseudorandom generators at all, did I? Yeah the article mentioned PRGs but most secure ciphers are designed to be (computationally) indistinguishable from random noise regardless of PRGs. We aren't just invoking PRGs to make encryption schemes. That would be ridiculous.

**Comment by zasdfgbnm** [comment] 2017-09-18 14:14
@Mygod 
> However due to the fact that all encryption schemes use pseudo-random generators, this hypothesis is not always true in practice. Each application employs its own ciphering scheme for packets
encryption. These schemes utilize pseudo-random algorithms which bear distinct patterns. These patterns can be used to distinguish applications from one another.

Yes, I totally agree with you here that this explanation is ridiculous and the author clearly does not understand  computational indistinguishability well.

I'm just saying that, although ciphers are transformations that the output is computationally  indistinguishable from each other given that the input is uniform distribution, it is still possible sniff protocol because this is a different problem from distinguishing two pseudo-random functions.

**Comment by wongsyrone** [comment] 2017-10-06 13:34
who can download this: The Random Forest Based Detection of Shadowsock's Traffic

http://ieeexplore.ieee.org/document/8048116/

**Comment by wongsyrone** [comment] 2017-10-06 14:33
@madeye @Mygod 

download and save as pdf file

![the random forest based detection of shadowsock s traffic pdf](https://user-images.githubusercontent.com/5462232/31282762-2017a10c-aae6-11e7-9fe1-08e731ff777c.jpg)

**Comment by zeptoTantalum** [comment] 2017-10-06 14:38
I'm a bit involved in the field of deep learning. This paper really confuses me. If I'm not mistaken, there are using CNN and SAE on the content of a single packet, instead of sequences of packets. In this case, how could they distinguish between Vimeo and Youtube, both of which uses HTTPS? Since they are working on a single packet, most of those packets are completely encrypted with no extra information.
I wonder if anyone can spare some time to investigate this dataset, reproduce the result, and find out what exactly their model has learned.
And @wongsyrone, I can download this file, but I need to ensure there is nothing like digital watermark to track me.

**Comment by wongsyrone** [comment] 2017-10-06 15:08
confused me as well.

another one try to identify Tor traffic
may contain what we need: http://ieeexplore.ieee.org/document/8048117/

**Comment by zeptoTantalum** [comment] 2017-10-06 15:15
@wongsyrone @madeye Seems this paper follows a pretty normal pattern for Machine Learning applications. It's not a amazing one, it just brings up the problems again, which has led to a lot of argument among those work against GFW:
Is it possible to identify Shadowsocks traffic, only by extracting features from network traffic?
That's the problem, whether they are using CNN/Auto-encoder/MLP/Random forest/SVM doesn't really matter.

**Comment by wongsyrone** [comment] 2017-10-06 15:20
These days, many people claim their Shadowsocks are down for hours and we don't know how. Sad.

**Comment by zeptoTantalum** [comment] 2017-10-06 15:44
@wongsyrone 
Personally, I am a bit suspicious what @breakwa11 has claimed. The problem is no one really knows how GFW works.
@breakwa11 has done a lot of works trying to discover the network traffic features of Shadowsocks/v2ray/obfs4, those features are basically from the length, direction and timestamp of a packet. And the way she propose to hide those feature is to randomize the length of those packet. However, it's hard to believe connection in real world really has packet with a almost uniform distribution among different length. It gonna just introduce another kind of feature.

**Comment by zeptoTantalum** [comment] 2017-10-06 15:54
If it is really possible to identify shadowsocks, via packet length, a better way might be to use machine learning to learn a generation model for the packet length pattern of a "normal" (WordPress, maybe?) website, and use this pattern to generate the length of TCP transport unit. But this really sounds complex, and whether it is necessary is unknown.

**Comment by zeptoTantalum** [comment] 2017-10-06 16:05
The best way to config shadowsocks, from my opinion, is to purchase a domain, setup a personal website, , using tls, and reverse proxy to shadowsocks via websocket, and use CloudFlare CDN. Ignoring traffic patterns related to packet length, even if we are doing this, it is still a little suspicous: You are connecting to a very unpopular domain name (revealed by SNI) for a long time, and with a surprisingly high traffic. This can be only resolved by the method used in Tor Meek. However, CDN supporting HTTP host header over SNI is very expensive. So there might be no "perfect" way to break GFW.

**Comment by wongsyrone** [comment] 2017-10-07 01:14
@zeptoTantalum 

> is to purchase a domain, setup a personal website, , using tls

similar to v2ray, do you have any idea on it?

**Comment by zasdfgbnm** [comment] 2017-10-07 03:13
Do we really need to worry about deep learning based packet sniffing? GFW is something that should work at a rate close to link speed. Deep learning is slow and I don't think it is possible to use deep learning methods to look at every international packet.

**Comment by zeptoTantalum** [comment] 2017-10-07 07:20
@wongsyrone 
https://github.com/shadowsocks/simple-obfs/pull/74
seems simple-obfs already support it?
@zasdfgbnm 
Using deep learning to detect the content of every packet sounds impossible, but it's still possible to just record the network activity, and use a Maching Learning model to analyze them periodically.
Deep Learning is not always that slow, huge models like Vgg/ResNet can have tens/hundereds of millions of parameters are slow but they will use much simplier ANN architectures for the GFW. And there are still "traditional" ML methods available.
That being said, I still doesn't know if they really use ML to build GFW.

**Comment by DarienRaymond** [comment] 2017-10-07 18:50
@zeptoTantalum 
Sadly it is not a true WebSocket. Easily detectable.

**Closed** 2017-10-09 08:27 UTC

**Comment by cmmei** [comment] 2017-10-11 10:16
@wongsyrone  https://sci-hub.bz/10.1109/IHMSC.2017.132  for *the random forest based detection of shadowsocks's traffic*

**Comment by wongsyrone** [comment] 2017-10-11 12:51
Thanks. But http://ieeexplore.ieee.org/document/8048117/ is more interesting, while most people ignored it.

**Comment by Mygod** [comment] 2017-10-12 04:49
@wongsyrone Papers these authors spammed are far less interesting than the one you originally posted.

**Comment by Mygod** [comment] 2017-10-13 04:58
Just to clarify: the paper from the original thread classifies Tor traffic without pluggable transport. This is something GFW already can do back in 2011 without deep learning. ([source](https://trac.torproject.org/projects/tor/ticket/4744))

**Comment by wongsyrone** [comment] 2017-10-13 08:39
Might inspired by http://ieeexplore.ieee.org/document/7249493/

**Comment by wongsyrone** [comment] 2017-10-13 08:42
another one: http://ieeexplore.ieee.org/document/7120915/

**Comment by Mygod** [comment] 2017-10-14 05:06
Not sure why you're bring up these. For 7249493, it's basically learning network traffic behavior under a wireless setting where every packet is broadcasted. This is much harder to do for the Internet.

For 7120915:

>The proposed covert channel has the following limitations.
>First, it can only be used to transmit small amount of auxiliary
>data, but cannot be used to transfer data of large size.
>Transferring big amount of data in the covert channel is
>very inefficient and easy to be detected...

**Comment by klzgrad** [comment] 2017-11-03 10:34
Guys need to look harder. More relevant are the papers from the same lab.

This `A multi-granularity heuristic-combining approach for censorship circumvention activity identification` is an example of flow analysis of freegate. This `Website fingerprinting attack on anonymity networks based on profile hidden markov model` appears to have replicated *Traffic Analysis of the HTTP Protocol over TLS*, a sequential flavor of flow analysis using HMM. The dude in the lab is not an idiot and these are definitely respectable work.

**Comment by Mygod** [comment] 2017-11-03 17:41
Flow analysis is generally expensive to implement on country-scale firewalls. The second one is less relevant. By the way if they really want to attack anonymity networks, they should target Tor instead. Shadowsocks only offers a moderate amount of anonymity protections.

**Comment by klzgrad** [comment] 2017-11-03 18:25
I've made the same point in another issue but I'll post it again. Flow analysis at nation state level is not as expensive as you claimed otherwise you'd wonder how is GFW even able to perform deep keyword pattern matching which is surely more expensive than analysis of aggregate data being an order of magnitude less than the actual traffic. `High Performance & Real-time Traffic Analysis in Large Scale Networks` from 2010 had some data points about the orders of magnitudes - they deployed DPI boxes at CSTNet of 10G backbone capacity with 90K flows/second collected and 4 PCs for data analysis. The compute grid at CNCERT is surely much larger and the problem at hand is also clearly scalable in nature and after 7 years you can bet they only got better. Again, shadowsocks would not be the main adversarial targets of these heavy-weight technologies developed with huge budget - malware and botnets and cyber warfare are. I agree there may be other reasons for which we do not pursue more traffic obfuscation but clearly this traffic analysis is a real threat.

**Comment by klzgrad** [comment] 2017-11-06 07:53
Some more data points on the performance of statistical traffic analysis:
> Although training machine learning classifiers can be
computationally complex, the classification of an incoming
sample can usually be efficiently computed. For
our l1-logistic regression model, a naive Go implementation
was able to classify 22,171 flows/second on a single
core VM and 116,632 flows/second on a 16-core VM
running on top of an Intel Xeon E7-2870s at 2.4 GHz.

from `Enhanced Telemetry for Encrypted Threat Analytics`, authored by the people behind Cisco Stealthwatch.
